/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarVisitaRouteImport } from './routes/agendar-visita'
import { Route as EnsinoRouteImport } from './routes/ensino'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as InfraestruturaRouteImport } from './routes/infraestrutura'
import { Route as MatriculasRouteImport } from './routes/matriculas'
import { Route as OColegioRouteImport } from './routes/o-colegio'
import { Route as VidaNoColegioRouteImport } from './routes/vida-no-colegio'
import { Route as EnsinoIndexRouteImport } from './routes/ensino.index'
import { Route as EnsinoEducacaoInfantilRouteImport } from './routes/ensino.educacao-infantil'
import { Route as EnsinoEnsinoMedioRouteImport } from './routes/ensino.ensino-medio'
import { Route as EnsinoFundamentalIRouteImport } from './routes/ensino.fundamental-i'
import { Route as EnsinoFundamentalIiRouteImport } from './routes/ensino.fundamental-ii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarVisitaRoute = AgendarVisitaRouteImport.update({
  id: '/agendar-visita',
  path: '/agendar-visita',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinoRoute = EnsinoRouteImport.update({
  id: '/ensino',
  path: '/ensino',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraestruturaRoute = InfraestruturaRouteImport.update({
  id: '/infraestrutura',
  path: '/infraestrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculasRoute = MatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => rootRouteImport,
} as any)
const OColegioRoute = OColegioRouteImport.update({
  id: '/o-colegio',
  path: '/o-colegio',
  getParentRoute: () => rootRouteImport,
} as any)
const VidaNoColegioRoute = VidaNoColegioRouteImport.update({
  id: '/vida-no-colegio',
  path: '/vida-no-colegio',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsinoIndexRoute = EnsinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnsinoRoute,
} as any)
const EnsinoEducacaoInfantilRoute = EnsinoEducacaoInfantilRouteImport.update({
  id: '/educacao-infantil',
  path: '/educacao-infantil',
  getParentRoute: () => EnsinoRoute,
} as any)
const EnsinoEnsinoMedioRoute = EnsinoEnsinoMedioRouteImport.update({
  id: '/ensino-medio',
  path: '/ensino-medio',
  getParentRoute: () => EnsinoRoute,
} as any)
const EnsinoFundamentalIRoute = EnsinoFundamentalIRouteImport.update({
  id: '/fundamental-i',
  path: '/fundamental-i',
  getParentRoute: () => EnsinoRoute,
} as any)
const EnsinoFundamentalIiRoute = EnsinoFundamentalIiRouteImport.update({
  id: '/fundamental-ii',
  path: '/fundamental-ii',
  getParentRoute: () => EnsinoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar-visita': typeof AgendarVisitaRoute
  '/ensino': typeof EnsinoRouteWithChildren
  '/familia': typeof FamiliaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/matriculas': typeof MatriculasRoute
  '/o-colegio': typeof OColegioRoute
  '/vida-no-colegio': typeof VidaNoColegioRoute
  '/ensino/educacao-infantil': typeof EnsinoEducacaoInfantilRoute
  '/ensino/ensino-medio': typeof EnsinoEnsinoMedioRoute
  '/ensino/fundamental-i': typeof EnsinoFundamentalIRoute
  '/ensino/fundamental-ii': typeof EnsinoFundamentalIiRoute
  '/ensino/': typeof EnsinoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar-visita': typeof AgendarVisitaRoute
  '/familia': typeof FamiliaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/matriculas': typeof MatriculasRoute
  '/o-colegio': typeof OColegioRoute
  '/vida-no-colegio': typeof VidaNoColegioRoute
  '/ensino/educacao-infantil': typeof EnsinoEducacaoInfantilRoute
  '/ensino/ensino-medio': typeof EnsinoEnsinoMedioRoute
  '/ensino/fundamental-i': typeof EnsinoFundamentalIRoute
  '/ensino/fundamental-ii': typeof EnsinoFundamentalIiRoute
  '/ensino': typeof EnsinoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar-visita': typeof AgendarVisitaRoute
  '/ensino': typeof EnsinoRouteWithChildren
  '/familia': typeof FamiliaRoute
  '/infraestrutura': typeof InfraestruturaRoute
  '/matriculas': typeof MatriculasRoute
  '/o-colegio': typeof OColegioRoute
  '/vida-no-colegio': typeof VidaNoColegioRoute
  '/ensino/educacao-infantil': typeof EnsinoEducacaoInfantilRoute
  '/ensino/ensino-medio': typeof EnsinoEnsinoMedioRoute
  '/ensino/fundamental-i': typeof EnsinoFundamentalIRoute
  '/ensino/fundamental-ii': typeof EnsinoFundamentalIiRoute
  '/ensino/': typeof EnsinoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar-visita'
    | '/ensino'
    | '/familia'
    | '/infraestrutura'
    | '/matriculas'
    | '/o-colegio'
    | '/vida-no-colegio'
    | '/ensino/educacao-infantil'
    | '/ensino/ensino-medio'
    | '/ensino/fundamental-i'
    | '/ensino/fundamental-ii'
    | '/ensino/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar-visita'
    | '/familia'
    | '/infraestrutura'
    | '/matriculas'
    | '/o-colegio'
    | '/vida-no-colegio'
    | '/ensino/educacao-infantil'
    | '/ensino/ensino-medio'
    | '/ensino/fundamental-i'
    | '/ensino/fundamental-ii'
    | '/ensino'
  id:
    | '__root__'
    | '/'
    | '/agendar-visita'
    | '/ensino'
    | '/familia'
    | '/infraestrutura'
    | '/matriculas'
    | '/o-colegio'
    | '/vida-no-colegio'
    | '/ensino/educacao-infantil'
    | '/ensino/ensino-medio'
    | '/ensino/fundamental-i'
    | '/ensino/fundamental-ii'
    | '/ensino/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarVisitaRoute: typeof AgendarVisitaRoute
  EnsinoRoute: typeof EnsinoRouteWithChildren
  FamiliaRoute: typeof FamiliaRoute
  InfraestruturaRoute: typeof InfraestruturaRoute
  MatriculasRoute: typeof MatriculasRoute
  OColegioRoute: typeof OColegioRoute
  VidaNoColegioRoute: typeof VidaNoColegioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar-visita': {
      id: '/agendar-visita'
      path: '/agendar-visita'
      fullPath: '/agendar-visita'
      preLoaderRoute: typeof AgendarVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensino': {
      id: '/ensino'
      path: '/ensino'
      fullPath: '/ensino'
      preLoaderRoute: typeof EnsinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infraestrutura': {
      id: '/infraestrutura'
      path: '/infraestrutura'
      fullPath: '/infraestrutura'
      preLoaderRoute: typeof InfraestruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriculas': {
      id: '/matriculas'
      path: '/matriculas'
      fullPath: '/matriculas'
      preLoaderRoute: typeof MatriculasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-colegio': {
      id: '/o-colegio'
      path: '/o-colegio'
      fullPath: '/o-colegio'
      preLoaderRoute: typeof OColegioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vida-no-colegio': {
      id: '/vida-no-colegio'
      path: '/vida-no-colegio'
      fullPath: '/vida-no-colegio'
      preLoaderRoute: typeof VidaNoColegioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensino/': {
      id: '/ensino/'
      path: '/'
      fullPath: '/ensino/'
      preLoaderRoute: typeof EnsinoIndexRouteImport
      parentRoute: typeof EnsinoRoute
    }
    '/ensino/educacao-infantil': {
      id: '/ensino/educacao-infantil'
      path: '/educacao-infantil'
      fullPath: '/ensino/educacao-infantil'
      preLoaderRoute: typeof EnsinoEducacaoInfantilRouteImport
      parentRoute: typeof EnsinoRoute
    }
    '/ensino/ensino-medio': {
      id: '/ensino/ensino-medio'
      path: '/ensino-medio'
      fullPath: '/ensino/ensino-medio'
      preLoaderRoute: typeof EnsinoEnsinoMedioRouteImport
      parentRoute: typeof EnsinoRoute
    }
    '/ensino/fundamental-i': {
      id: '/ensino/fundamental-i'
      path: '/fundamental-i'
      fullPath: '/ensino/fundamental-i'
      preLoaderRoute: typeof EnsinoFundamentalIRouteImport
      parentRoute: typeof EnsinoRoute
    }
    '/ensino/fundamental-ii': {
      id: '/ensino/fundamental-ii'
      path: '/fundamental-ii'
      fullPath: '/ensino/fundamental-ii'
      preLoaderRoute: typeof EnsinoFundamentalIiRouteImport
      parentRoute: typeof EnsinoRoute
    }
  }
}

interface EnsinoRouteChildren {
  EnsinoEducacaoInfantilRoute: typeof EnsinoEducacaoInfantilRoute
  EnsinoEnsinoMedioRoute: typeof EnsinoEnsinoMedioRoute
  EnsinoFundamentalIRoute: typeof EnsinoFundamentalIRoute
  EnsinoFundamentalIiRoute: typeof EnsinoFundamentalIiRoute
  EnsinoIndexRoute: typeof EnsinoIndexRoute
}

const EnsinoRouteChildren: EnsinoRouteChildren = {
  EnsinoEducacaoInfantilRoute: EnsinoEducacaoInfantilRoute,
  EnsinoEnsinoMedioRoute: EnsinoEnsinoMedioRoute,
  EnsinoFundamentalIRoute: EnsinoFundamentalIRoute,
  EnsinoFundamentalIiRoute: EnsinoFundamentalIiRoute,
  EnsinoIndexRoute: EnsinoIndexRoute,
}

const EnsinoRouteWithChildren =
  EnsinoRoute._addFileChildren(EnsinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarVisitaRoute: AgendarVisitaRoute,
  EnsinoRoute: EnsinoRouteWithChildren,
  FamiliaRoute: FamiliaRoute,
  InfraestruturaRoute: InfraestruturaRoute,
  MatriculasRoute: MatriculasRoute,
  OColegioRoute: OColegioRoute,
  VidaNoColegioRoute: VidaNoColegioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
